### ISSUE TITLE
A/B Testing

### ISSUE THREAD

**Issue by lshamis** [gdikov/hypertunity#41]
From the documentation, the `update` method seems to take absolute reward values for samples. I'm wondering if there's a way to give relative rewards, i.e. A/B testing.

For context, I'm trying to hypertune an RL reward signal. I'd like to produce 2+ sets of hyperparams, train the models, sample trajectories from each model, and let a human decide which is better.

Thanks

**Comment by gdikov** [comment]
Hi @lshamis, I am not sure that I understand you entirely but I will try my best, please feel free to dismiss my suggestions (and elaborate why) if they are not applicable. One thing that you could do is to run two parallel optimisations with the A- and the B-features respectively, e.g. 
```python
domain_a = Domain({"common_var": [0, 1], "a": [2, 3]})
domain_b = Domain({"common_var": [0, 1], "b": [3, 4]})
```
This way you would not have to care about any overlap, constraints over the domains and so on, but of course optimisation history of A will not influence B and vice versa. 
If you want to model the dependence of the two options you will have to include them in a single domain and use code to decide what to do with the samples, e.g:
```python
domain_ab = Domain({"common_var": [0, 1], "a": [2, 3], "b": [3, 4]})
sample = ...    # obtain sample from the domain_ab, e.g. using the BayesianOptimisation optimiser
# do stuff with sample["common_var"]
if random.uniform(0, 1) < prob_a:
    # do stuff with sample["a"]
else:
    # do stuff with sample["b"]
```
If you want the BO optimiser to decide for you the `prob_a` then you could use a categorical variable:
```python
domain_ab = Domain({"common_var": [0, 1], "ab": {"a", "b"}, "a": [2, 3], "b": [3, 4]})
if sample["ab"] == "a":
    # do stuff with sample["a"]
else:
    # do stuff with sample["b"]
```
If neither of these works, could you give me an illustrative example of what, ideally, hypertunity should be able to do?

Cheers

**Comment by lshamis** [comment]
Thanks for the response. Unfortunately, I don't think it quite fits my problem. I might be able to iteratively bisect the space...

Let me try to explain my problem in more depth.
I have only one `Domain` (with continuous variables that sum to one). I'd like to get two samples of the continuous variables and have a human choose a "winner".

Here's some code that clearly wont work, but may show what I'm thinking:
```py
domain = Domain({"some_var": [0, 1], "other_var": [0, 1]})
bo = BayesianOptimisation(domain=domain)
samples = bo.run_step(batch_size=2, minimise=True)
better_index = ask_human(samples[0], samples[1])
if better_index == 0:
  bo.update(samples, [1, 0])
else:
  bo.update(samples, [0, 1])
```

**Comment by gdikov** [comment]
Thanks for the code sample, it makes it clearer. However I fail to understand, if this is what you desire, why do you think that this code should not work? The snippet you provided should be able to run successfully, as you sample twice and then update the optimiser with the two scores. 
One minor detail, though, is that in your example you have set `minimise=True` but `samples[better_index]` has higher score which is the opposite of what you want, I guess.

**Comment by lshamis** [comment]
D'oh! (about the `minimise=True`)

I assumed the `BayesianOptimisation` would expect a sample evaluations to have a fixed distribution. With my setup, there is a drift in the distribution over the update iterations.

I'll try it out and report back.

**Comment by gdikov** [comment]
I assume that you got your problem resolved and I will close this issue. Feel free to reopen if you have further questions.
