### ISSUE TITLE
Invoke function from script

### ISSUE THREAD

**Issue by davidt0x** [gdikov/hypertunity#42]
Thanks for the great library. I was playing around with it and tried to invoke a function from a script by creating a job. It seems the func_name argument to get_callable_from_script is not used and instead main is called. 

https://github.com/gdikov/hypertunity/blob/30efcf84804e6ea52b2019455c80e119bab89a10/hypertunity/scheduling/jobs.py#L113

Should it not be something like:

```
return getattr(module, func_name)(*args)
```

Or am I missing something?

Thanks,
Dave

**Comment by gdikov** [comment]
Hi Dave,

You are not missing anything, it should be as you suggested. There are tests for that but of course I used the name `main` and they passed... Would you like to open a PR or shall I patch it?

Cheers,
Georgi

**Comment by davidt0x** [comment]
Sure, just put up a PR. Thanks for the quick response.

**Comment by gdikov** [comment]
I am closing this issue as it has been resolved with your fix. I may release a new version in PyPI soon but as of now the best would be to install it from source. Thanks again.
